/**
 * 301s from the old WordPress site (fireonthebayou.com), so links and search
 * rankings carry over at launch. Generated from its sitemaps (110 URLs).
 * Project/client pages map to their new screening room where one exists.
 * The old blog posts were generic SEO articles; they point home.
 */
export const legacyRedirects: { source: string; destination: string; permanent: true }[] = [
  { source: "/project/reily-foods-commercial", destination: "/work/reily-foods", permanent: true },
  { source: "/project/aucoin-hart-commercial-part-2", destination: "/work/aucoin-hart", permanent: true },
  { source: "/project/aucoin-hart-commercial", destination: "/work/aucoin-hart", permanent: true },
  { source: "/project/dressed-blue-plate-mayonnaise", destination: "/work/blue-plate", permanent: true },
  { source: "/project/team-depot-new-orleans", destination: "/work/home-depot", permanent: true },
  { source: "/project/red-bull-featuring-new-creation-brass-band", destination: "/work/red-bull", permanent: true },
  { source: "/project/nothing-beats-louisiana", destination: "/work/blue-runner", permanent: true },
  { source: "/project/bigger-than-monday", destination: "/work/blue-runner", permanent: true },
  { source: "/project/rouses-markets-crawfish", destination: "/work/rouses", permanent: true },
  { source: "/project/rouses-markets-feels-like-home-holiday", destination: "/work/rouses", permanent: true },
  { source: "/project/rouses-chris-noel", destination: "/work/rouses", permanent: true },
  { source: "/project/make-today-an-audubon-day", destination: "/work/audubon", permanent: true },
  { source: "/project/lifes-more-fun-with-seafood-2", destination: "/work/acme-oyster-house", permanent: true },
  { source: "/project/sazerac-house-anthem", destination: "/work/sazerac-house", permanent: true },
  { source: "/project/life-has-a-log-in", destination: "/work/city-park", permanent: true },
  { source: "/project/russel-athletic-mark-ingram-brand-video", destination: "/work/russell-athletic", permanent: true },
  { source: "/project/crystal-hot-sauce", destination: "/work/crystal-hot-sauce", permanent: true },
  { source: "/project/louisiana-economic-development", destination: "/work/louisiana-economic-development", permanent: true },
  { source: "/project/:slug*", destination: "/work", permanent: true },
  { source: "/client/louisiana-economic-development", destination: "/work/louisiana-economic-development", permanent: true },
  { source: "/client/blue-runner-foods-commercials-and-videos", destination: "/work/blue-runner", permanent: true },
  { source: "/client/crystal-hot-sauce-commercial-new-orleans", destination: "/work/crystal-hot-sauce", permanent: true },
  { source: "/client/home-depot", destination: "/work/home-depot", permanent: true },
  { source: "/client/red-bull", destination: "/work/red-bull", permanent: true },
  { source: "/client/reily-foods", destination: "/work/reily-foods", permanent: true },
  { source: "/client/louisiana-rouses-supermarket-video-production", destination: "/work/rouses", permanent: true },
  { source: "/client/russel-athletic", destination: "/work/russell-athletic", permanent: true },
  { source: "/client/acme-oyster-house", destination: "/work/acme-oyster-house", permanent: true },
  { source: "/client/audubon-nature-institute", destination: "/work/audubon", permanent: true },
  { source: "/client/new-orleans-city-park", destination: "/work/city-park", permanent: true },
  { source: "/client/sazerac-house", destination: "/work/sazerac-house", permanent: true },
  { source: "/client/blue-plate-mayo-brand-video-produced-in-new-orleans", destination: "/work/blue-plate", permanent: true },
  { source: "/client/aucoin-hart", destination: "/work/aucoin-hart", permanent: true },
  { source: "/client/:slug*", destination: "/work", permanent: true },
  { source: "/industry/:slug*", destination: "/work", permanent: true },
  { source: "/purpose/:slug*", destination: "/work", permanent: true },
  { source: "/director/:slug*", destination: "/about", permanent: true },
  { source: "/meet-the-crew", destination: "/about", permanent: true },
  { source: "/faqs-on-video-production", destination: "/process#faq", permanent: true },
  { source: "/capabilities", destination: "/services", permanent: true },
  { source: "/capabilities/:slug*", destination: "/services", permanent: true },
  { source: "/blog", destination: "/work", permanent: true },
  { source: "/sitemap", destination: "/", permanent: true },
  { source: "/new-orleans-video-production-company-fire-on-the-bayou-old", destination: "/", permanent: true },
  { source: "/how-to-choose-the-best-commercial-video-production-in-louisiana", destination: "/", permanent: true },
  { source: "/videography-trends-in-new-orleans-you-should-know", destination: "/", permanent: true },
  { source: "/what-to-expect-from-video-production-companies-in-new-orleans", destination: "/", permanent: true },
  { source: "/the-best-videographers-in-new-orleans-what-to-look-for-when-hiring", destination: "/", permanent: true },
  { source: "/affordable-video-production-services-in-louisiana-how-to-find-the-best-deals", destination: "/", permanent: true },
  { source: "/what-to-expect-from-video-production-companies-new-orleans", destination: "/", permanent: true },
  { source: "/exploring-the-best-commercial-video-production-locations-in-louisiana", destination: "/", permanent: true },
  { source: "/the-best-new-orleans-video-production-companies-for-your-next-project", destination: "/", permanent: true },
  { source: "/brand-impact-with-a-business-videographer", destination: "/", permanent: true },
  { source: "/how-to-advertise-on-youtube", destination: "/", permanent: true },
  { source: "/why-new-orleans-video-production-is-essential-for-your-brand", destination: "/", permanent: true },
  { source: "/whats-hot-in-commercial-video-production-in-la-right-now", destination: "/", permanent: true },
  { source: "/best-places-to-shoot-video-in-new-orleans", destination: "/", permanent: true },
  { source: "/video-production-in-new-orleans-expert-services-with-local-flair", destination: "/", permanent: true },
  { source: "/top-tv-advertising-production-companies-for-your-campaign", destination: "/", permanent: true },
  { source: "/how-brand-videos-elevate-your-business", destination: "/", permanent: true },
];
